//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphicTestProject.Classes.Controller {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings_Keyboard : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings_Keyboard defaultInstance = ((Settings_Keyboard)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings_Keyboard())));
        
        public static Settings_Keyboard Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S")]
        public global::System.Windows.Forms.Keys moveDown {
            get {
                return ((global::System.Windows.Forms.Keys)(this["moveDown"]));
            }
            set {
                this["moveDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W")]
        public global::System.Windows.Forms.Keys moveUp {
            get {
                return ((global::System.Windows.Forms.Keys)(this["moveUp"]));
            }
            set {
                this["moveUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A")]
        public global::System.Windows.Forms.Keys moveLeft {
            get {
                return ((global::System.Windows.Forms.Keys)(this["moveLeft"]));
            }
            set {
                this["moveLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D")]
        public global::System.Windows.Forms.Keys moveRight {
            get {
                return ((global::System.Windows.Forms.Keys)(this["moveRight"]));
            }
            set {
                this["moveRight"] = value;
            }
        }
    }
}
